# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dev-lint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "prettier"
          - "@lokalise/eslint-config-frontend"

      testing:
        patterns:
          - "expect-type"
      types:
        patterns:
          - "@types/*"
      vite:
        patterns:
          - "vite"
          - "vite-*"
          - "@vitejs/*"
          - "vitest"
          - "@vitest/*"
      semantic-release:
        patterns:
          - "semantic-release"
          - "semantic-release-*"
          - "@semantic-release/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
